DB_WebSite/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView, LogoutView
from django.urls import path, include

from WebPage import views
from WebPage.views import ParentCreateView, ParentUpdateView, ParentDeleteView, ParentListView, RoleAssignView, \
    UserUpdateView, UserListView
from WebPage.views import ChildCreateView, ChildUpdateView, ChildDeleteView, ChildListView
from WebPage.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n'))

]
urlpatterns += i18n_patterns(
    path('', HomeView.as_view(), name='home'),
    path('register/', views.register, name='register'),
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/password_change/',
         PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('accounts/password_change/done/',
         PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    path('accounts/logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/update/', UserUpdateView.as_view(), name='user_form'),
    path('users/<int:pk>/assign_role/', RoleAssignView.as_view(), name='role_assign_form'),

    path('parents/', ParentListView.as_view(), name='parent_list'),
    path('parents/create/', ParentCreateView.as_view(), name='parent_create'),
    path('parents/<int:pk>/update/', ParentUpdateView.as_view(), name='parent_update'),
    path('parents/<int:pk>/delete/', ParentDeleteView.as_view(), name='parent_delete'),

    path('children/', ChildListView.as_view(), name='child_list'),
    path('children/create/', ChildCreateView.as_view(), name='child_create'),
    path('children/<int:pk>/update/', ChildUpdateView.as_view(), name='child_update'),
    path('children/<int:pk>/delete/', ChildDeleteView.as_view(), name='child_delete'),

)

WebPage/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.utils import timezone


class Parent(models.Model):
    name = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=20)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Child(models.Model):
    name = models.CharField(max_length=100)
    birth_date = models.DateField()
    group = models.CharField(max_length=50)
    parent = models.ForeignKey(Parent, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class UserSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, default=3)
    login_time = models.DateTimeField(default=timezone.now)
    logout_time = models.DateTimeField(null=True, blank=True)
    duration = models.DurationField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} ({self.group.name}) - {self.login_time}"

WebPage/forms.py
from django import forms
from .models import Parent, Child
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class ParentForm(forms.ModelForm):
    class Meta:
        model = Parent
        fields = ['name', 'contact_number', 'address']

class ChildForm(forms.ModelForm):
    class Meta:
        model = Child
        fields = ['name', 'birth_date', 'group', 'parent']

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['parent'].queryset = Parent.objects.all()


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

WebPage/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView

from .forms import ParentForm, ChildForm
from .forms import RegisterForm
from .models import Parent, Child


def manager_required(user):
    return user.groups.filter(name='Manager').exists()


def admin_required(user):
    return user.groups.filter(name='Administrator').exists()
def user_required(user):
    return user.groups.filter(name='User').exists()

class HomeView(TemplateView):
    template_name = 'home.html'


# Читання записів (Read)
class ParentListView(ListView):
    model = Parent
    template_name = 'parent/parent_list.html'
    context_object_name = "parents"

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ChildListView(ListView):
    model = Child
    template_name = 'child/child_list.html'
    context_object_name = "childs"

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

# Створення запису (Create)
class ParentCreateView(CreateView):
    model = Parent
    form_class = ParentForm
    success_url = reverse_lazy('parent_list')
    template_name = 'parent/parent_form.html'

    @method_decorator(user_passes_test(manager_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ChildCreateView(CreateView):
    model = Child
    form_class = ChildForm
    success_url = reverse_lazy('child_list')
    template_name = 'child/child_form.html'

    @method_decorator(user_passes_test(manager_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# Оновлення запису (Update)
class ParentUpdateView(UpdateView):
    model = Parent
    form_class = ParentForm
    success_url = reverse_lazy('parent_list')
    template_name = 'parent/parent_form.html'

    @method_decorator(user_passes_test(manager_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ChildUpdateView(UpdateView):
    model = Child
    form_class = ChildForm
    success_url = reverse_lazy('child_list')
    template_name = 'child/child_form.html'

    @method_decorator(user_passes_test(manager_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# Видалення запису (Delete)
class ParentDeleteView(DeleteView):
    model = Parent
    success_url = reverse_lazy('parent_list')
    template_name = 'parent/parent_confirm_delete.html'

    @method_decorator(user_passes_test(manager_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ChildDeleteView(DeleteView):
    model = Child
    success_url = reverse_lazy('child_list')
    template_name = 'child/child_confirm_delete.html'

    @method_decorator(user_passes_test(manager_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class UserListView(ListView):
    model = User
    template_name = 'roles/user_list.html'
    context_object_name = 'users'

    @method_decorator(user_passes_test(admin_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class UserUpdateView(UpdateView):
    model = User
    fields = ['username', 'email', 'first_name', 'last_name']
    template_name = 'roles/user_form.html'
    success_url = reverse_lazy('user_list')

    @method_decorator(user_passes_test(admin_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class RoleAssignView(UpdateView):
    model = User
    fields = ['username', 'groups']
    template_name = 'roles/role_assign_form.html'
    success_url = reverse_lazy('user_list')

    @method_decorator(user_passes_test(admin_required))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')

            if User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists():
                return render(request, 'registration/register.html', {'form': form,
                                                                      'error_message': 'User already exists. Please choose a different username or email.'})

            user = form.save()
            user.refresh_from_db()
            group = Group.objects.get(name='User')
            user.groups.add(group)
            user.save()
            raw_password = form.cleaned_data.get('password1')

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = RegisterForm()
    return render(request, 'registration/register.html', {'form': form})

WebPage/templates/parent/parent_confirm_delete.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans "Delete Parent" %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>{% trans "Delete Parent" %}</h1>
        <p>{% trans "Are you sure you want to delete this parent: {{ parent.name }}?" %}</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
            <a href="{% url 'parent_list' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
    </div>
</body>
</html>

WebPage/templates/parent/parent_form.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if form.instance.pk %}{% trans "Edit Parent" %}{% else %}{% trans "Add Parent" %}{% endif %}</title>
    <link rel="stylesheet" href="{% static 'css/forms-parent.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <h1 class="form-title">{% if form.instance.pk %}{% trans "Edit Parent" %}{% else %}{% trans "Add Parent" %}{% endif %}</h1>
            <label for="id_name">{% trans "Name" %}:</label>
            {{ form.name }}
            <label for="id_contact_number">{% trans "Contact Number" %}:</label>
            {{ form.contact_number }}
            <label for="id_address">{% trans "Address" %}:</label>
            {{ form.address }}
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            <a href="{% url 'parent_list' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
        <div class="image-container">
            <img src="{% static 'images/parent.png' %}" alt="{% trans 'Placeholder Image' %}">
        </div>
    </div>
</body>
</html>

WebPage/templates/parent/parent_list.html
{% extends 'base_layout.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<body>
    <div class="container" style="margin-left: 200px; padding-top: 20px;">
        <h1>{% trans "List of Parents" %}</h1>
        <a href="{% url 'parent_create' %}" class="btn btn-primary mb-3">{% trans "Add Parent" %}</a>
        <table class="table">
            <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Contact Number" %}</th>
                <th>{% trans "Address" %}</th>
                <th>{% trans "Actions" %}</th>
            </tr>
            </thead>
            <tbody>
                {% for parent in parents %}
                    <tr>
                        <td>{{ parent.name }}</td>
                        <td>{{ parent.contact_number }}</td>
                        <td>{{ parent.address }}</td>
                        <td>
                            <a href="{% url 'parent_update' parent.pk %}" class="btn btn-primary btn-sm">{% trans "Edit" %}</a>
                            <a href="{% url 'parent_delete' parent.pk %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
{% endblock %}